### ISSUE TITLE
[Issue] A.10.1.1. Penggunaan Fungsi fmt.Print()

### ISSUE THREAD

**Issue by gedenata** [novalagung/dasarpemrogramangolang#19]
Topic : https://dasarpemrogramangolang.novalagung.com/10-konstanta.html

I think `A.10.1.1.` not related to constant topic, it's should explained in `https://dasarpemrogramangolang.novalagung.com/37-string-format.html` or create new topic e.g. **Format I/O**.

Better more explain about https://blog.golang.org/constants. IMHO.

**Comment by novalagung** [comment]
yes it is unrelated. however I believe it is effective since our target audience is not an experienced engineer.

basically, simple api like `fmt.Print` is mandatory in hello world or variable/constant topic-related chapters, and also inbetween chapter A.10 and A.37, both `fmt.Print` and `fmt.Println` is used a lot.

it is definitelly **not ok** if audience has to wait until chapter A.37 just to know about `fmt.Print`.
