### ISSUE TITLE
Page load is too slow

### ISSUE THREAD

**Issue by afifurrohman-id** [novalagung/dasarpemrogramangolang#237]
# Description
When have bad internet connection and first load page is too slow, Maybe because have a lot `JavaScript` send to browser

# Reproduce 
**Lighthouse Result:**
![image](https://github.com/novalagung/dasarpemrogramangolang/assets/118882411/fd4903bf-3246-49d1-8c16-f0d9ea2c3890)

**Comment by afifurrohman-id** [comment]
How about use `GitHub pages` instead of SSG ?

Great content btw, is very helpful people like me

**Comment by novalagung** [comment]
This website originally uses github pages.

We currently moved to our own server to handle incorrect article url redirection (we have gone many url changes in the past).

Moving back to github pages is great but I need to think how to handle the url redirection, otherwise so many people who use the old version of the book will see 404 error when clicking certain article url

**Comment by novalagung** [comment]
The best solution around for now is to eliminate the part that causes slowness instead of moving back to github pages.

I will see what I can. Thanks for raising the issue btw
